### ISSUE TITLE
Decrease notes octave label

### ISSUE THREAD

**Issue by maizy** [maizy/sightreading.training#14]
C5 -> C4 ...

related: https://github.com/leafo/sightreading.training/issues/44

**Comment by fedorl** [comment]
@maizy @leafo Will the change be deployed to https://sightreading.training site? 
As a side note, you did really excellent job with this app! It beats hands down most of commercial ones. I only wish it was in typescript so I can contribute )

**Comment by maizy** [comment]
@fedorl I'm not planning to propose this future into upstream (https://github.com/leafo/sightreading.training), because it's controversial.

But I'm going to create publicly available static version of my fork in github pages (https://github.com/maizy/sightreading.training/issues/21)
